# Site settings
title: Markus Wrang
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Markus Wrang
user_subtitle: Software Engineering Student
user_description: Software Engineering Student at Gothenburg University
email: markus.wrang_94@hotmail.com
github_username:  wrang308
linkedin_username:  markus-wrang-159478144

# Google-analytics
google-analytics:
  id: "UA-98748109-1"

sass:
  sass_dir: css
  style: compressed
